heroes = (
		{
			'name': 'NAME',
			'id': 'ID',
			'push': 'Push',
			'nuker': 'Nuker',
			'disabler': 'Disabler',
			'initiator': 'Initiate',
			'carry': 'Carry',
			'escape': 'Escape',
			'durable': 'Durable',
			'jungler': 'Jungler',
			'outpush': 'Outpush',
			'complexity': 'Complexity',
			'melee': 'Melee',
		},
		{
			'name': 'Anti_Mage',
			'id': 1,
			'push': 0,
			'nuker': 1,
			'disabler': 0,
			'initiator': 1,
			'carry': 2,
			'escape': 2,
			'durable': 1,
			'jungler': 1,
			'outpush': 0,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Axe',
			'id': 2,
			'push': 0,
			'nuker': 1,
			'disabler': 2,
			'initiator': 2,
			'carry': 1,
			'escape': 0,
			'durable': 2,
			'jungler': 2,
			'outpush': 1,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Bane',
			'id': 3,
			'push': 0,
			'nuker': 1,
			'disabler': 3,
			'initiator': 2,
			'carry': 1,
			'escape': 0,
			'durable': 0,
			'jungler': 0,
			'outpush': 0,
			'complexity': 2,
			'melee': 'false',
		},
		{
			'name': 'Bloodseeker',
			'id': 4,
			'push': 1,
			'nuker': 2,
			'disabler': 1,
			'initiator': 2,
			'carry': 2,
			'escape': 1,
			'durable': 1,
			'jungler': 2,
			'outpush': 1,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Crystal_Maiden',
			'id': 5,
			'push': 0,
			'nuker': 1,
			'disabler': 1,
			'initiator': 1,
			'carry': 0,
			'escape': 0,
			'durable': 0,
			'jungler': 0,
			'outpush': 1,
			'complexity': 1,
			'melee': 'false',
		},
		{
			'name': 'Drow_Ranger',
			'id': 6,
			'push': 2,
			'nuker': 1,
			'disabler': 1,
			'initiator': 0,
			'carry': 2,
			'escape': 0,
			'durable': 0,
			'jungler': 0,
			'outpush': 0,
			'complexity': 1,
			'melee': 'false',
		},
		{
			'name': 'Earthshaker',
			'id': 7,
			'push': 0,
			'nuker': 2,
			'disabler': 2,
			'initiator': 2,
			'carry': 1,
			'escape': 0,
			'durable': 0,
			'jungler': 0,
			'outpush': 1,
			'complexity': 2,
			'melee': 'true',
		},
		{
			'name': 'Juggernaut',
			'id': 8,
			'push': 2,
			'nuker': 2,
			'disabler': 0,
			'initiator': 1,
			'carry': 3,
			'escape': 2,
			'durable': 2,
			'jungler': 1,
			'outpush': 1,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Mirana',
			'id': 9,
			'push': 1,
			'nuker': 1,
			'disabler': 1,
			'initiator': 1,
			'carry': 1,
			'escape': 2,
			'durable': 0,
			'jungler': 1,
			'outpush': 1,
			'complexity': 2,
			'melee': 'false',
		},
		{
			'name': 'Morphling',
			'id': 10,
			'push': 1,
			'nuker': 2,
			'disabler': 1,
			'initiator': 1,
			'carry': 3,
			'escape': 2,
			'durable': 3,
			'jungler': 0,
			'outpush': 1,
			'complexity': 3,
			'melee': 'false',
		},
		{
			'name': 'Shadow_Fiend',
			'id': 11,
			'push': 1,
			'nuker': 3,
			'disabler': 0,
			'initiator': 1,
			'carry': 2,
			'escape': 0,
			'durable': 1,
			'jungler': 3,
			'outpush': 2,
			'complexity': 2,
			'melee': 'false',
		},
		{
			'name': 'Phantom_Lancer',
			'id': 12,
			'push': 1,
			'nuker': 1,
			'disabler': 0,
			'initiator': 0,
			'carry': 3,
			'escape': 2,
			'durable': 2,
			'jungler': 2,
			'outpush': 0,
			'complexity': 2,
			'melee': 'true',
		},
		{
			'name': 'Puck',
			'id': 13,
			'push': 1,
			'nuker': 2,
			'disabler': 2,
			'initiator': 3,
			'carry': 1,
			'escape': 3,
			'durable': 0,
			'jungler': 0,
			'outpush': 1,
			'complexity': 2,
			'melee': 'false',
		},
		{
			'name': 'Pudge',
			'id': 14,
			'push': 1,
			'nuker': 1,
			'disabler': 2,
			'initiator': 1,
			'carry': 1,
			'escape': 2,
			'durable': 2,
			'jungler': 0,
			'outpush': 1,
			'complexity': 2,
			'melee': 'true',
		},
		{
			'name': 'Razor',
			'id': 15,
			'push': 1,
			'nuker': 2,
			'disabler': 0,
			'initiator': 0,
			'carry': 2,
			'escape': 0,
			'durable': 1,
			'jungler': 0,
			'outpush': 1,
			'complexity': 1,
			'melee': 'false',
		},
		{
			'name': 'Sand_King',
			'id': 16,
			'push': 0,
			'nuker': 2,
			'disabler': 1,
			'initiator': 2,
			'carry': 0,
			'escape': 1,
			'durable': 0,
			'jungler': 1,
			'outpush': 1,
			'complexity': 2,
			'melee': 'true',
		},
		{
			'name': 'Storm_Spirit',
			'id': 17,
			'push': 1,
			'nuker': 3,
			'disabler': 1,
			'initiator': 3,
			'carry': 2,
			'escape': 3,
			'durable': 0,
			'jungler': 1,
			'outpush': 2,
			'complexity': 3,
			'melee': 'false',
		},
		{
			'name': 'Sven',
			'id': 18,
			'push': 2,
			'nuker': 2,
			'disabler': 1,
			'initiator': 2,
			'carry': 2,
			'escape': 1,
			'durable': 2,
			'jungler': 2,
			'outpush': 1,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Tiny',
			'id': 19,
			'push': 1,
			'nuker': 3,
			'disabler': 1,
			'initiator': 1,
			'carry': 2,
			'escape': 0,
			'durable': 1,
			'jungler': 0,
			'outpush': 1,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Vengeful_Spirit',
			'id': 20,
			'push': 1,
			'nuker': 1,
			'disabler': 1,
			'initiator': 2,
			'carry': 1,
			'escape': 1,
			'durable': 0,
			'jungler': 0,
			'outpush': 1,
			'complexity': 1,
			'melee': 'false',
		},
		{
			'name': 'Windranger',
			'id': 21,
			'push': 2,
			'nuker': 2,
			'disabler': 2,
			'initiator': 2,
			'carry': 2,
			'escape': 3,
			'durable': 1,
			'jungler': 0,
			'outpush': 1,
			'complexity': 2,
			'melee': 'false',
		},
		{
			'name': 'Zeus',
			'id': 22,
			'push': 0,
			'nuker': 3,
			'disabler': 0,
			'initiator': 1,
			'carry': 2,
			'escape': 0,
			'durable': 0,
			'jungler': 1,
			'outpush': 1,
			'complexity': 1,
			'melee': 'false',
		},
		{
			'name': 'Kunkka',
			'id': 23,
			'push': 0,
			'nuker': 2,
			'disabler': 2,
			'initiator': 2,
			'carry': 2,
			'escape': 0,
			'durable': 1,
			'jungler': 0,
			'outpush': 2,
			'complexity': 2,
			'melee': 'true',
		},
		{
			'name': 'NoSuchHero',
			'id': 24,
			'push': 0,
			'nuker': 0,
			'disabler': 0,
			'initiator': 0,
			'carry': 0,
			'escape': 0,
			'durable': 0,
			'jungler': 0,
			'outpush': 0,
			'complexity': 0,
			'melee': 'false',
		},
		{
			'name': 'Lina',
			'id': 25,
			'push': 1,
			'nuker': 3,
			'disabler': 1,
			'initiator': 1,
			'carry': 2,
			'escape': 0,
			'durable': 0,
			'jungler': 1,
			'outpush': 1,
			'complexity': 1,
			'melee': 'false',
		},
		{
			'name': 'Lion',
			'id': 26,
			'push': 0,
			'nuker': 2,
			'disabler': 3,
			'initiator': 2,
			'carry': 1,
			'escape': 2,
			'durable': 0,
			'jungler': 0,
			'outpush': 1,
			'complexity': 1,
			'melee': 'false',
		},
		{
			'name': 'Shadow_Shaman',
			'id': 27,
			'push': 3,
			'nuker': 1,
			'disabler': 2,
			'initiator': 2,
			'carry': 1,
			'escape': 0,
			'durable': 0,
			'jungler': 0,
			'outpush': 1,
			'complexity': 1,
			'melee': 'false',
		},
		{
			'name': 'Slardar',
			'id': 28,
			'push': 0,
			'nuker': 2,
			'disabler': 1,
			'initiator': 2,
			'carry': 2,
			'escape': 1,
			'durable': 1,
			'jungler': 0,
			'outpush': 0,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Tidehunter',
			'id': 29,
			'push': 0,
			'nuker': 0,
			'disabler': 1,
			'initiator': 1,
			'carry': 1,
			'escape': 0,
			'durable': 2,
			'jungler': 0,
			'outpush': 0,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Witch_Doctor',
			'id': 30,
			'push': 0,
			'nuker': 2,
			'disabler': 2,
			'initiator': 0,
			'carry': 1,
			'escape': 0,
			'durable': 1,
			'jungler': 0,
			'outpush': 1,
			'complexity': 1,
			'melee': 'false',
		},
		{
			'name': 'Lich',
			'id': 31,
			'push': 1,
			'nuker': 2,
			'disabler': 0,
			'initiator': 1,
			'carry': 1,
			'escape': 0,
			'durable': 1,
			'jungler': 0,
			'outpush': 2,
			'complexity': 1,
			'melee': 'false',
		},
		{
			'name': 'Riki',
			'id': 32,
			'push': 0,
			'nuker': 0,
			'disabler': 1,
			'initiator': 1,
			'carry': 2,
			'escape': 2,
			'durable': 1,
			'jungler': 0,
			'outpush': 0,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Enigma',
			'id': 33,
			'push': 2,
			'nuker': 1,
			'disabler': 2,
			'initiator': 2,
			'carry': 1,
			'escape': 0,
			'durable': 0,
			'jungler': 2,
			'outpush': 2,
			'complexity': 2,
			'melee': 'false',
		},
		{
			'name': 'Tinker',
			'id': 34,
			'push': 1,
			'nuker': 3,
			'disabler': 1,
			'initiator': 1,
			'carry': 2,
			'escape': 0,
			'durable': 0,
			'jungler': 2,
			'outpush': 3,
			'complexity': 2,
			'melee': 'false',
		},
		{
			'name': 'Sniper',
			'id': 35,
			'push': 2,
			'nuker': 2,
			'disabler': 0,
			'initiator': 1,
			'carry': 3,
			'escape': 0,
			'durable': 0,
			'jungler': 1,
			'outpush': 2,
			'complexity': 1,
			'melee': 'false',
		},
		{
			'name': 'Necrophos',
			'id': 36,
			'push': 0,
			'nuker': 2,
			'disabler': 1,
			'initiator': 1,
			'carry': 2,
			'escape': 2,
			'durable': 0,
			'jungler': 0,
			'outpush': 0,
			'complexity': 1,
			'melee': 'false',
		},
		{
			'name': 'Warlock',
			'id': 37,
			'push': 2,
			'nuker': 1,
			'disabler': 1,
			'initiator': 2,
			'carry': 1,
			'escape': 0,
			'durable': 1,
			'jungler': 0,
			'outpush': 1,
			'complexity': 1,
			'melee': 'false',
		},
		{
			'name': 'Beastmaster',
			'id': 38,
			'push': 2,
			'nuker': 1,
			'disabler': 2,
			'initiator': 2,
			'carry': 1,
			'escape': 0,
			'durable': 1,
			'jungler': 0,
			'outpush': 1,
			'complexity': 2,
			'melee': 'true',
		},
		{
			'name': 'Queen_of_Pain',
			'id': 39,
			'push': 0,
			'nuker': 3,
			'disabler': 0,
			'initiator': 2,
			'carry': 2,
			'escape': 3,
			'durable': 0,
			'jungler': 2,
			'outpush': 1,
			'complexity': 2,
			'melee': 'false',
		},
		{
			'name': 'Venomancer',
			'id': 40,
			'push': 1,
			'nuker': 1,
			'disabler': 0,
			'initiator': 1,
			'carry': 1,
			'escape': 0,
			'durable': 0,
			'jungler': 0,
			'outpush': 1,
			'complexity': 1,
			'melee': 'false',
		},
		{
			'name': 'Faceless_Void',
			'id': 41,
			'push': 1,
			'nuker': 1,
			'disabler': 3,
			'initiator': 3,
			'carry': 3,
			'escape': 3,
			'durable': 1,
			'jungler': 1,
			'outpush': 0,
			'complexity': 2,
			'melee': 'true',
		},
		{
			'name': 'Wraith_King',
			'id': 42,
			'push': 1,
			'nuker': 2,
			'disabler': 2,
			'initiator': 2,
			'carry': 2,
			'escape': 0,
			'durable': 3,
			'jungler': 1,
			'outpush': 0,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Death_Prophet',
			'id': 43,
			'push': 2,
			'nuker': 1,
			'disabler': 1,
			'initiator': 0,
			'carry': 2,
			'escape': 1,
			'durable': 2,
			'jungler': 1,
			'outpush': 1,
			'complexity': 1,
			'melee': 'false',
		},
		{
			'name': 'Phantom_Assassin',
			'id': 44,
			'push': 0,
			'nuker': 1,
			'disabler': 0,
			'initiator': 1,
			'carry': 2,
			'escape': 1,
			'durable': 1,
			'jungler': 0,
			'outpush': 0,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Pugna',
			'id': 45,
			'push': 3,
			'nuker': 2,
			'disabler': 1,
			'initiator': 0,
			'carry': 2,
			'escape': 1,
			'durable': 1,
			'jungler': 1,
			'outpush': 2,
			'complexity': 2,
			'melee': 'false',
		},
		{
			'name': 'Templar_Assassin',
			'id': 46,
			'push': 1,
			'nuker': 2,
			'disabler': 0,
			'initiator': 1,
			'carry': 2,
			'escape': 1,
			'durable': 3,
			'jungler': 2,
			'outpush': 1,
			'complexity': 2,
			'melee': 'false',
		},
		{
			'name': 'Viper',
			'id': 47,
			'push': 1,
			'nuker': 1,
			'disabler': 1,
			'initiator': 1,
			'carry': 2,
			'escape': 0,
			'durable': 2,
			'jungler': 0,
			'outpush': 1,
			'complexity': 1,
			'melee': 'false',
		},
		{
			'name': 'Luna',
			'id': 48,
			'push': 3,
			'nuker': 2,
			'disabler': 0,
			'initiator': 1,
			'carry': 2,
			'escape': 0,
			'durable': 2,
			'jungler': 2,
			'outpush': 0,
			'complexity': 1,
			'melee': 'false',
		},
		{
			'name': 'Dragon_Knight',
			'id': 49,
			'push': 1,
			'nuker': 1,
			'disabler': 1,
			'initiator': 1,
			'carry': 2,
			'escape': 0,
			'durable': 3,
			'jungler': 0,
			'outpush': 1,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Dazzle',
			'id': 50,
			'push': 2,
			'nuker': 0,
			'disabler': 0,
			'initiator': 0,
			'carry': 2,
			'escape': 3,
			'durable': 3,
			'jungler': 0,
			'outpush': 0,
			'complexity': 1,
			'melee': 'false',
		},
		{
			'name': 'Clockwerk',
			'id': 51,
			'push': 0,
			'nuker': 0,
			'disabler': 2,
			'initiator': 3,
			'carry': 1,
			'escape': 2,
			'durable': 1,
			'jungler': 0,
			'outpush': 1,
			'complexity': 2,
			'melee': 'true',
		},
		{
			'name': 'Leshrac',
			'id': 52,
			'push': 2,
			'nuker': 2,
			'disabler': 1,
			'initiator': 0,
			'carry': 2,
			'escape': 0,
			'durable': 0,
			'jungler': 2,
			'outpush': 1,
			'complexity': 1,
			'melee': 'false',
		},
		{
			'name': 'Natures_Prophet',
			'id': 53,
			'push': 3,
			'nuker': 1,
			'disabler': 1,
			'initiator': 2,
			'carry': 2,
			'escape': 2,
			'durable': 1,
			'jungler': 3,
			'outpush': 2,
			'complexity': 2,
			'melee': 'false',
		},
		{
			'name': 'Lifestealer',
			'id': 54,
			'push': 1,
			'nuker': 1,
			'disabler': 0,
			'initiator': 1,
			'carry': 2,
			'escape': 3,
			'durable': 3,
			'jungler': 3,
			'outpush': 0,
			'complexity': 2,
			'melee': 'true',
		},
		{
			'name': 'Dark_Seer',
			'id': 55,
			'push': 1,
			'nuker': 1,
			'disabler': 0,
			'initiator': 1,
			'carry': 1,
			'escape': 2,
			'durable': 1,
			'jungler': 2,
			'outpush': 1,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Clinkz',
			'id': 56,
			'push': 2,
			'nuker': 2,
			'disabler': 1,
			'initiator': 1,
			'carry': 2,
			'escape': 1,
			'durable': 0,
			'jungler': 0,
			'outpush': 0,
			'complexity': 2,
			'melee': 'false',
		},
		{
			'name': 'Omniknight',
			'id': 57,
			'push': 1,
			'nuker': 1,
			'disabler': 0,
			'initiator': 1,
			'carry': 3,
			'escape': 3,
			'durable': 3,
			'jungler': 0,
			'outpush': 1,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Enchantress',
			'id': 58,
			'push': 2,
			'nuker': 1,
			'disabler': 0,
			'initiator': 1,
			'carry': 1,
			'escape': 1,
			'durable': 2,
			'jungler': 3,
			'outpush': 1,
			'complexity': 2,
			'melee': 'false',
		},
		{
			'name': 'Huskar',
			'id': 59,
			'push': 1,
			'nuker': 2,
			'disabler': 0,
			'initiator': 2,
			'carry': 2,
			'escape': 1,
			'durable': 2,
			'jungler': 0,
			'outpush': 0,
			'complexity': 1,
			'melee': 'false',
		},
		{
			'name': 'Night_Stalker',
			'id': 60,
			'push': 0,
			'nuker': 2,
			'disabler': 3,
			'initiator': 2,
			'carry': 2,
			'escape': 2,
			'durable': 1,
			'jungler': 0,
			'outpush': 0,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Broodmother',
			'id': 61,
			'push': 3,
			'nuker': 1,
			'disabler': 0,
			'initiator': 1,
			'carry': 2,
			'escape': 2,
			'durable': 1,
			'jungler': 3,
			'outpush': 0,
			'complexity': 2,
			'melee': 'true',
		},
		{
			'name': 'Bounty_Hunter',
			'id': 62,
			'push': 0,
			'nuker': 1,
			'disabler': 0,
			'initiator': 1,
			'carry': 1,
			'escape': 1,
			'durable': 0,
			'jungler': 3,
			'outpush': 0,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Weaver',
			'id': 63,
			'push': 2,
			'nuker': 1,
			'disabler': 0,
			'initiator': 1,
			'carry': 2,
			'escape': 3,
			'durable': 1,
			'jungler': 0,
			'outpush': 1,
			'complexity': 2,
			'melee': 'false',
		},
		{
			'name': 'Jakiro',
			'id': 64,
			'push': 3,
			'nuker': 1,
			'disabler': 1,
			'initiator': 1,
			'carry': 0,
			'escape': 1,
			'durable': 0,
			'jungler': 0,
			'outpush': 3,
			'complexity': 1,
			'melee': 'false',
		},
		{
			'name': 'Batrider',
			'id': 65,
			'push': 0,
			'nuker': 1,
			'disabler': 1,
			'initiator': 2,
			'carry': 1,
			'escape': 2,
			'durable': 0,
			'jungler': 2,
			'outpush': 1,
			'complexity': 2,
			'melee': 'false',
		},
		{
			'name': 'Chen',
			'id': 66,
			'push': 2,
			'nuker': 1,
			'disabler': 0,
			'initiator': 0,
			'carry': 0,
			'escape': 2,
			'durable': 2,
			'jungler': 3,
			'outpush': 0,
			'complexity': 3,
			'melee': 'false',
		},
		{
			'name': 'Spectre',
			'id': 67,
			'push': 0,
			'nuker': 1,
			'disabler': 0,
			'initiator': 1,
			'carry': 3,
			'escape': 2,
			'durable': 2,
			'jungler': 0,
			'outpush': 0,
			'complexity': 2,
			'melee': 'true',
		},
		{
			'name': 'Ancient_Apparition',
			'id': 68,
			'push': 0,
			'nuker': 1,
			'disabler': 1,
			'initiator': 1,
			'carry': 1,
			'escape': 0,
			'durable': 0,
			'jungler': 0,
			'outpush': 1,
			'complexity': 2,
			'melee': 'false',
		},
		{
			'name': 'Doom',
			'id': 69,
			'push': 1,
			'nuker': 2,
			'disabler': 3,
			'initiator': 1,
			'carry': 2,
			'escape': 2,
			'durable': 3,
			'jungler': 2,
			'outpush': 0,
			'complexity': 2,
			'melee': 'true',
		},
		{
			'name': 'Ursa',
			'id': 70,
			'push': 0,
			'nuker': 2,
			'disabler': 0,
			'initiator': 2,
			'carry': 2,
			'escape': 1,
			'durable': 3,
			'jungler': 0,
			'outpush': 0,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Spirit_Breaker',
			'id': 71,
			'push': 0,
			'nuker': 1,
			'disabler': 3,
			'initiator': 3,
			'carry': 2,
			'escape': 1,
			'durable': 1,
			'jungler': 0,
			'outpush': 0,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Gyrocopter',
			'id': 72,
			'push': 1,
			'nuker': 2,
			'disabler': 1,
			'initiator': 1,
			'carry': 2,
			'escape': 0,
			'durable': 1,
			'jungler': 2,
			'outpush': 2,
			'complexity': 1,
			'melee': 'false',
		},
		{
			'name': 'Alchemist',
			'id': 73,
			'push': 1,
			'nuker': 1,
			'disabler': 1,
			'initiator': 1,
			'carry': 2,
			'escape': 0,
			'durable': 2,
			'jungler': 3,
			'outpush': 1,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Invoker',
			'id': 74,
			'push': 2,
			'nuker': 3,
			'disabler': 2,
			'initiator': 1,
			'carry': 2,
			'escape': 3,
			'durable': 0,
			'jungler': 1,
			'outpush': 2,
			'complexity': 3,
			'melee': 'false',
		},
		{
			'name': 'Silencer',
			'id': 75,
			'push': 0,
			'nuker': 0,
			'disabler': 2,
			'initiator': 1,
			'carry': 1,
			'escape': 1,
			'durable': 0,
			'jungler': 0,
			'outpush': 0,
			'complexity': 2,
			'melee': 'false',
		},
		{
			'name': 'Outworld_Devourer',
			'id': 76,
			'push': 0,
			'nuker': 2,
			'disabler': 1,
			'initiator': 1,
			'carry': 2,
			'escape': 2,
			'durable': 1,
			'jungler': 0,
			'outpush': 0,
			'complexity': 2,
			'melee': 'false',
		},
		{
			'name': 'Lycan',
			'id': 77,
			'push': 3,
			'nuker': 2,
			'disabler': 0,
			'initiator': 1,
			'carry': 2,
			'escape': 1,
			'durable': 2,
			'jungler': 2,
			'outpush': 1,
			'complexity': 2,
			'melee': 'true',
		},
		{
			'name': 'Brewmaster',
			'id': 78,
			'push': 0,
			'nuker': 1,
			'disabler': 2,
			'initiator': 1,
			'carry': 1,
			'escape': 2,
			'durable': 2,
			'jungler': 0,
			'outpush': 0,
			'complexity': 3,
			'melee': 'true',
		},
		{
			'name': 'Shadow_Demon',
			'id': 79,
			'push': 1,
			'nuker': 1,
			'disabler': 2,
			'initiator': 1,
			'carry': 1,
			'escape': 2,
			'durable': 0,
			'jungler': 0,
			'outpush': 1,
			'complexity': 2,
			'melee': 'false',
		},
		{
			'name': 'Lone_Druid',
			'id': 80,
			'push': 3,
			'nuker': 1,
			'disabler': 1,
			'initiator': 1,
			'carry': 2,
			'escape': 2,
			'durable': 3,
			'jungler': 3,
			'outpush': 1,
			'complexity': 3,
			'melee': 'false',
		},
		{
			'name': 'Chaos_Knight',
			'id': 81,
			'push': 1,
			'nuker': 2,
			'disabler': 1,
			'initiator': 1,
			'carry': 3,
			'escape': 1,
			'durable': 2,
			'jungler': 0,
			'outpush': 0,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Meepo',
			'id': 82,
			'push': 0,
			'nuker': 2,
			'disabler': 2,
			'initiator': 1,
			'carry': 3,
			'escape': 2,
			'durable': 1,
			'jungler': 2,
			'outpush': 0,
			'complexity': 3,
			'melee': 'true',
		},
		{
			'name': 'Treant_Protector',
			'id': 83,
			'push': 1,
			'nuker': 0,
			'disabler': 3,
			'initiator': 1,
			'carry': 2,
			'escape': 2,
			'durable': 2,
			'jungler': 1,
			'outpush': 0,
			'complexity': 2,
			'melee': 'true',
		},
		{
			'name': 'Ogre_Magi',
			'id': 84,
			'push': 2,
			'nuker': 2,
			'disabler': 2,
			'initiator': 0,
			'carry': 1,
			'escape': 0,
			'durable': 2,
			'jungler': 0,
			'outpush': 1,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Undying',
			'id': 85,
			'push': 1,
			'nuker': 1,
			'disabler': 0,
			'initiator': 2,
			'carry': 1,
			'escape': 2,
			'durable': 3,
			'jungler': 0,
			'outpush': 1,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Rubick',
			'id': 86,
			'push': 1,
			'nuker': 1,
			'disabler': 1,
			'initiator': 1,
			'carry': 1,
			'escape': 1,
			'durable': 0,
			'jungler': 0,
			'outpush': 1,
			'complexity': 3,
			'melee': 'false',
		},
		{
			'name': 'Disruptor',
			'id': 87,
			'push': 0,
			'nuker': 1,
			'disabler': 3,
			'initiator': 3,
			'carry': 2,
			'escape': 2,
			'durable': 0,
			'jungler': 0,
			'outpush': 1,
			'complexity': 2,
			'melee': 'false',
		},
		{
			'name': 'Nyx_Assassin',
			'id': 88,
			'push': 0,
			'nuker': 2,
			'disabler': 2,
			'initiator': 2,
			'carry': 1,
			'escape': 2,
			'durable': 2,
			'jungler': 0,
			'outpush': 0,
			'complexity': 2,
			'melee': 'true',
		},
		{
			'name': 'Naga_Siren',
			'id': 89,
			'push': 2,
			'nuker': 1,
			'disabler': 2,
			'initiator': 1,
			'carry': 2,
			'escape': 3,
			'durable': 1,
			'jungler': 0,
			'outpush': 1,
			'complexity': 2,
			'melee': 'true',
		},
		{
			'name': 'Keeper_of_the_Light',
			'id': 90,
			'push': 2,
			'nuker': 1,
			'disabler': 1,
			'initiator': 1,
			'carry': 1,
			'escape': 1,
			'durable': 0,
			'jungler': 1,
			'outpush': 3,
			'complexity': 2,
			'melee': 'false',
		},
		{
			'name': 'Io',
			'id': 91,
			'push': 1,
			'nuker': 1,
			'disabler': 1,
			'initiator': 2,
			'carry': 1,
			'escape': 3,
			'durable': 2,
			'jungler': 1,
			'outpush': 0,
			'complexity': 3,
			'melee': 'false',
		},
		{
			'name': 'Visage',
			'id': 92,
			'push': 1,
			'nuker': 2,
			'disabler': 1,
			'initiator': 0,
			'carry': 1,
			'escape': 1,
			'durable': 2,
			'jungler': 1,
			'outpush': 0,
			'complexity': 3,
			'melee': 'false',
		},
		{
			'name': 'Slark',
			'id': 93,
			'push': 0,
			'nuker': 2,
			'disabler': 1,
			'initiator': 2,
			'carry': 3,
			'escape': 3,
			'durable': 1,
			'jungler': 1,
			'outpush': 0,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Medusa',
			'id': 94,
			'push': 1,
			'nuker': 1,
			'disabler': 1,
			'initiator': 0,
			'carry': 2,
			'escape': 3,
			'durable': 3,
			'jungler': 3,
			'outpush': 2,
			'complexity': 1,
			'melee': 'false',
		},
		{
			'name': 'Troll_Warlord',
			'id': 95,
			'push': 2,
			'nuker': 2,
			'disabler': 1,
			'initiator': 0,
			'carry': 2,
			'escape': 1,
			'durable': 2,
			'jungler': 2,
			'outpush': 0,
			'complexity': 2,
			'melee': 'false',
		},
		{
			'name': 'Centaur_Warrunner',
			'id': 96,
			'push': 0,
			'nuker': 2,
			'disabler': 2,
			'initiator': 2,
			'carry': 2,
			'escape': 3,
			'durable': 3,
			'jungler': 2,
			'outpush': 1,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Magnus',
			'id': 97,
			'push': 1,
			'nuker': 1,
			'disabler': 2,
			'initiator': 3,
			'carry': 2,
			'escape': 2,
			'durable': 1,
			'jungler': 1,
			'outpush': 1,
			'complexity': 2,
			'melee': 'true',
		},
		{
			'name': 'Timbersaw',
			'id': 98,
			'push': 0,
			'nuker': 3,
			'disabler': 0,
			'initiator': 2,
			'carry': 3,
			'escape': 3,
			'durable': 2,
			'jungler': 2,
			'outpush': 2,
			'complexity': 2,
			'melee': 'true',
		},
		{
			'name': 'Bristleback',
			'id': 99,
			'push': 0,
			'nuker': 2,
			'disabler': 0,
			'initiator': 1,
			'carry': 2,
			'escape': 1,
			'durable': 3,
			'jungler': 2,
			'outpush': 1,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Tusk',
			'id': 100,
			'push': 0,
			'nuker': 2,
			'disabler': 2,
			'initiator': 2,
			'carry': 1,
			'escape': 3,
			'durable': 1,
			'jungler': 0,
			'outpush': 1,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Skywrath_Mage',
			'id': 101,
			'push': 0,
			'nuker': 3,
			'disabler': 1,
			'initiator': 1,
			'carry': 0,
			'escape': 0,
			'durable': 0,
			'jungler': 0,
			'outpush': 0,
			'complexity': 1,
			'melee': 'false',
		},
		{
			'name': 'Abaddon',
			'id': 102,
			'push': 1,
			'nuker': 1,
			'disabler': 0,
			'initiator': 1,
			'carry': 2,
			'escape': 3,
			'durable': 3,
			'jungler': 1,
			'outpush': 1,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Elder_Titan',
			'id': 103,
			'push': 1,
			'nuker': 2,
			'disabler': 1,
			'initiator': 1,
			'carry': 2,
			'escape': 2,
			'durable': 1,
			'jungler': 1,
			'outpush': 1,
			'complexity': 2,
			'melee': 'true',
		},
		{
			'name': 'Legion_Commander',
			'id': 104,
			'push': 1,
			'nuker': 1,
			'disabler': 2,
			'initiator': 3,
			'carry': 2,
			'escape': 2,
			'durable': 2,
			'jungler': 3,
			'outpush': 1,
			'complexity': 1,
			'melee': 'true',
		},
		{
			'name': 'Techies',
			'id': 105,
			'push': 1,
			'nuker': 1,
			'disabler': 1,
			'initiator': 1,
			'carry': 1,
			'escape': 0,
			'durable': 0,
			'jungler': 0,
			'outpush': 3,
			'complexity': 2,
			'melee': 'false',
		},
		{
			'name': 'Ember_Spirit',
			'id': 106,
			'push': 0,
			'nuker': 2,
			'disabler': 1,
			'initiator': 2,
			'carry': 2,
			'escape': 3,
			'durable': 1,
			'jungler': 2,
			'outpush': 1,
			'complexity': 2,
			'melee': 'true',
		},
		{
			'name': 'Earth_Spirit',
			'id': 107,
			'push': 0,
			'nuker': 2,
			'disabler': 3,
			'initiator': 3,
			'carry': 2,
			'escape': 3,
			'durable': 1,
			'jungler': 0,
			'outpush': 1,
			'complexity': 3,
			'melee': 'true',
		},
		{
			'name': 'Underlord',
			'id': 108,
			'push': 1,
			'nuker': 1,
			'disabler': 1,
			'initiator': 1,
			'carry': 1,
			'escape': 2,
			'durable': 3,
			'jungler': 1,
			'outpush': 2,
			'complexity': 2,
			'melee': 'true',
		},
		{
			'name': 'Terrorblade',
			'id': 109,
			'push': 2,
			'nuker': 1,
			'disabler': 0,
			'initiator': 0,
			'carry': 3,
			'escape': 2,
			'durable': 2,
			'jungler': 1,
			'outpush': 0,
			'complexity': 2,
			'melee': 'true',
		},
		{
			'name': 'Phoenix',
			'id': 110,
			'push': 1,
			'nuker': 2,
			'disabler': 2,
			'initiator': 1,
			'carry': 1,
			'escape': 3,
			'durable': 2,
			'jungler': 0,
			'outpush': 1,
			'complexity': 2,
			'melee': 'false',
		},
		{
			'name': 'Oracle',
			'id': 111,
			'push': 0,
			'nuker': 1,
			'disabler': 2,
			'initiator': 0,
			'carry': 1,
			'escape': 3,
			'durable': 1,
			'jungler': 0,
			'outpush': 0,
			'complexity': 3,
			'melee': 'false',
		},
		{
			'name': 'Winter_Wyvern',
			'id': 112,
			'push': 1,
			'nuker': 2,
			'disabler': 2,
			'initiator': 2,
			'carry': 1,
			'escape': 2,
			'durable': 1,
			'jungler': 1,
			'outpush': 1,
			'complexity': 2,
			'melee': 'false',
		},
		{
			'name': 'Arc_Warden',
			'id': 113,
			'push': 2,
			'nuker': 1,
			'disabler': 1,
			'initiator': 0,
			'carry': 3,
			'escape': 2,
			'durable': 1,
			'jungler': 3,
			'outpush': 2,
			'complexity': 3,
			'melee': 'false',
		},
		{
			'name': 'Monkey_King',
			'id': 114,
			'push': 1,
			'nuker': 2,
			'disabler': 1,
			'initiator': 2,
			'carry': 2,
			'escape': 1,
			'durable': 2,
			'jungler': 1,
			'outpush': 1,
			'complexity': 2,
			'melee': 'true',
		},
		{
			'name': 'NoSuchHero',
			'id': 115,
			'push': 0,
			'nuker': 0,
			'disabler': 0,
			'initiator': 0,
			'carry': 0,
			'escape': 0,
			'durable': 0,
			'jungler': 0,
			'outpush': 0,
			'complexity': 0,
			'melee': 'false',
		},
		{
			'name': 'NoSuchHero',
			'id': 116,
			'push': 0,
			'nuker': 0,
			'disabler': 0,
			'initiator': 0,
			'carry': 0,
			'escape': 0,
			'durable': 0,
			'jungler': 0,
			'outpush': 0,
			'complexity': 0,
			'melee': 'false',
		},
		{
			'name': 'NoSuchHero',
			'id': 117,
			'push': 0,
			'nuker': 0,
			'disabler': 0,
			'initiator': 0,
			'carry': 0,
			'escape': 0,
			'durable': 0,
			'jungler': 0,
			'outpush': 0,
			'complexity': 0,
			'melee': 'false',
		},
		{
			'name': 'NoSuchHero',
			'id': 118,
			'push': 0,
			'nuker': 0,
			'disabler': 0,
			'initiator': 0,
			'carry': 0,
			'escape': 0,
			'durable': 0,
			'jungler': 0,
			'outpush': 0,
			'complexity': 0,
			'melee': 'false',
		},
		{
			'name': 'Dark_Willow',
			'id': 119,
			'push': 0,
			'nuker': 3,
			'disabler': 1,
			'initiator': 1,
			'carry': 1,
			'escape': 3,
			'durable': 2,
			'jungler': 0,
			'outpush': 1,
			'complexity': 2,
			'melee': 'false',
		},
		{
			'name': 'Pangolier',
			'id': 120,
			'push': 0,
			'nuker': 2,
			'disabler': 2,
			'initiator': 2,
			'carry': 1,
			'escape': 3,
			'durable': 2,
			'jungler': 1,
			'outpush': 2,
			'complexity': 2,
			'melee': 'true',
		}
)